language: cpp
sudo: require
dist: Xenial Xerus

os:
  - linux

compiler:
  - gcc

install:
  - sudo apt --yes install cmake git wget unzip libnuma-dev
  - sudo apt update
  - sudo apt dist-upgrade
  - wget -qO - http://repo.radeon.com/rocm/apt/debian/rocm.gpg.key | sudo apt-key add -
  - sudo sh -c 'echo deb [arch=amd64] http://repo.radeon.com/rocm/apt/debian/ xenial main > /etc/apt/sources.list.d/rocm.list'
  - sudo apt update
  - sudo apt install rocm-dkms

addons:
    apt:
        sources:
            - ubuntu-toolchain-r-test
        packages:
            - lcov
            - gcc-6
            - g++-6
            - cmake
  
branches:
  - master
  - develop

before_script:
  - git clone https://github.com/kiritigowda/help
  - cd help/neuralNetModelProfiler/scripts
  - python NNProfiler-setup.py -s test 
  - cmake -DCMAKE_C_FLAGS="-Wall -fprofile-arcs -ftest-coverage -std=c99" .

script: 
  - make 

after_success:


notifications:
  email:
        - kiritigowda@gmail.com
